import type { Metadata } from "next";
import "./globals.css";
import PageLayout from "@/app/page-layout";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <PageLayout>
          <div className="flex flex-col flex-grow">
            {children}
            <Footer />
          </div>
        </PageLayout>
      </body>
    </html>
  );
}
